# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_AD8Up2Isvr_zpei6GmzmkEXr1VOT9ja
"""

!pip install googletrans==3.1.0a0

from fnmatch import translate
from googletrans import Translator

translater = Translator()

out=translater.translate('मैं बढ़िया हूँ', dest='en')

print(out.text)

